### ISSUE TITLE
spotpy website is unreachable

### ISSUE THREAD

**Issue by ritviksahajpal** [thouska/spotpy#152]
Thanks for a great tool! The spotpy website at https://fb09-pasig.umwelt.uni-giessen.de/spotpy/ seems to be down since at least yesterday so I wanted to bring it to your attention.

**Comment by thouska** [comment]
Hi @ritviksahajpal ,
thank you for your message! We are currently running some larger updates on our server, which turned out to have some consequences for our webpages. This should be fixed soon. 
For the meantime, I can just provide you the unfortunatelly a bit unconvient way through the [doc markdown files](https://github.com/thouska/spotpy/tree/master/docs) here on github.

**Comment by ritviksahajpal** [comment]
thanks for your quick reply @thouska , this is very helpful!
