### ISSUE TITLE
bug if minbound = 0

### ISSUE THREAD

**Issue by TStella** [thouska/spotpy#172]
parameter.py, line 190:
when the minbound (or maxbound) of a parameter is set to 0, 
self.minbound = param_args.get('minbound') or _round_sig(np.min(sample)) will ignore the bound and use np.min(sample).

Why not to use 
self.minbound = param_args.get('minbound', _round_sig(np.min(sample)))
instead?

**Comment by thouska** [comment]
Hmm, I had to revert the above change, because it results in minbound getting set to None.

Are you sure with your statement that "self.minbound = param_args.get('minbound') or _round_sig(np.min(sample)) will ignore the bound and use np.min(sample)"?

**Comment by TStella** [comment]
Hi @thouska ,
first, thank you for your work :)

I'm trying to define a parameter as follows:
spotpy.parameter.Normal(name="parname", mean=0.6, stddev=0.2, optguess=0.6, minbound=0, maxbound=1)

The parameter value must be non negative, but

self.minbound = param_args.get('minbound') or _round_sig(np.min(sample))

is set to a negative value (the actual value depends on the sample). I think that param_args.get('minbound'), when minbound is 0, returns False and _round_sig(np.min(sample)) is therefore used.

Sorry for my previous suggestion of an unsuitable fix.

**Comment by philippkraft** [comment]
@TStella your analysis of the situation is totally correct and I am the guilty one for that code. I will submit today a pull request to fix that problem. Your solution did not work, because my complicated _ArgumentHelper fills the dictionary with None value for all keywords. I will include your case into the unit tests to ensure this bug will never happen again.
