### ISSUE TITLE
Error when running fast analysis because of _compute_first_order

### ISSUE THREAD

**Issue by IFuentesSR** [thouska/spotpy#198]
Hi, 
I'm trying the fast algorithm for a sensitivity analysis.
However, I'm getting an error due to the _compute_first_order function since one of the indices gives me equal to the size of the Sp variable.
Here is the issue: 
Sp[np.arange(1, M + 1) * int(omega) - 1]
which retrieves an index error:  index 991 is out of bounds of axis 0 with size 991.

I reckon I could fix it by subtracting 2 instead of 1.
Just to be sure, I'm using 17 variables, and the number of iterations that I'm running is 33745, according to the documentation:
N=(1+4M^2(1+(k−2)d))k

**Comment by thouska** [comment]
Hi @IFuentesSR 
thanks for your message. Is your `len(results)==33745`?
If so, the `_compute_first_order` function should work. If not, I would recommend to delete some lines at the end of your output file to get a number of lines with `len(results)%17==0.`
If the problem persists, I would need your spotpy-, python version as well as your OS type for further help.

**Comment by IFuentesSR** [comment]
Hi,
Yes, the length of results is 33745, and `len(results)%17==0` is True.
I tried python 2.7.15rc1 and 3.6.6, having the same error with both versions. The spotpy version is 1.3.30 and I'm running everything in Kubuntu 18.04.
Regards

**Comment by thouska** [comment]
Sorry for my late answer! Is this problem still existing? I tested the most recent version of spotpy with python 3.6 and was not able to reproduce this error. Feel free to re-open this issue if the problem is still persisting.

**Comment by MuellerSeb** [comment]
I often run into this error, if the number of repetitions in the FAST algorithm is to low. What confuses me, that this happens for example in a model with 5 parameters and using the formula from the documentation to calculate the number of fast repetitions:

    File "/usr/local/lib/python3.6/dist-packages/spotpy/algorithms/fast.py", line 181, in compute_first_order
        D1 = 2 * np.sum(Sp[np.arange(1, M + 1) * int(omega) - 1])

    IndexError: index 223 is out of bounds for axis 0 with size 223

Maybe this line should be adopted a bound-check..

**Comment by MuellerSeb** [comment]
Update:
In my case I found the problem. In my model the objective function produces rather high values for some parameter constellations > 65536 (max value for float16). Since the standard precision in the databases of spotpy is np.float16, this resulted in a lot of ``inf`` values in the DB. By setting

    db_precision=np.float64

in the instantiation of the FAST algorithm, I could solve the problem for me.

Maybe ``np.float16`` is a bit to restrictive as a standard value here:
https://github.com/thouska/spotpy/blob/269a5a7435f1e45d7ad90bb32d4ed9df89f77943/spotpy/algorithms/_algorithm.py#L210

Cheers,
Sebastian
