### ISSUE TITLE
Unexpected default behavior in SCEUA algorithm

### ISSUE THREAD

**Issue by dalmo1991** [thouska/spotpy#218]
Thank you for the great module. However some documentation is misleading (or I'm not finding the proper documentation).

I have encapsulated my model in a spotpy_setup object, implementing also my objectivefunction. I have noticed that, if I don't specify `alt_objfun = None` when I initialize the sampler, the algorithm uses the root mean square error. This should be specified also in the tutorials because the expected behavior is that it would use the implemented objectivefunction.

**Comment by thouska** [comment]
Hi @dalmo1991,
thank you for your message. Are you using the most recent version of spotpy (1.5.1)? From version 1.5 on, the keyword "alt_objfun" was removed, because it was indeed a bit unexpected behavior. From now on spotpy will always use the user defined/implemented objective function. I will update the documentation accordingly.

**Comment by dalmo1991** [comment]
Hi @thouska 
Thank you for the reply. I was using the version 1.4.6.
I will move to the new one.
