### ISSUE TITLE
Discrepances in the resulting CSV file using SCEUA with MPI parallelization

### ISSUE THREAD

**Issue by mop-mop** [thouska/spotpy#24]
Dear Spotpy-team,

I noticed some defective lines in the results.csv by using the SCEUA algorithm with MPI parallelization. This error is occurring beginning from the second up to the sixt line, depending on the optimization problem.

Personally, I use the algorithm to determine input parameters combined with another software, which could take a while when running. Due to this, it is possible to show you a temporary and the final CSV file. I observed for increasing repetitions an increasing amount of incorrect lines. As far as I can tell, the CSV file is written sequentially after each optimization step. Checking its contents during running the script does not show the defective lines, but only after the program is terminated. This may indicate that there is something wrong with the file access among the MPI processes. Maybe the file output stream is closed before the other processes have finished, who then again begin writing from the beginning from the file.

To provide a minimal example, you'll find attached a malfunctioning example for the Rosenbrock problem shipped with spotpy, including the incomplete CSV file. I can not provide a temporary CSV file since the optimization finishes too fast. Unfortunately, the error does not occur in each run, so you have to try it several times to reproduce it.

Is it possible to fix this?

Best regards,
Corinna
[rosenbrock_mpi_fail.zip](https://github.com/thouska/spotpy/files/621740/rosenbrock_mpi_fail.zip)
[FDS_temporary.zip](https://github.com/thouska/spotpy/files/621755/FDS_temporary.zip)

**Comment by gitporst** [comment]
Hey Corinna,

without checking your files, I think the easiest fix would be to disallow the the parallel processes to get file access. It should be better to collect the results from the processes first and then write it in the files.

Specifically, it would be necessary to take the call self.datawriter.save out of the loop (that is parallelized) and then loop over the collected results and call self.datawriter.save afterwards in a non-parallized loop.

I think the problem is not specific the sceua, so the fix should encompass all other algorithms. It should not be too difficult, though.

I will only be able to have a look at it in the next year. I know, that @thouska is currently not able to have a look at it, as well. So you might attempt to fix it yourself or wait for some more weeks.

Really sorry for the delay.

**Comment by philippkraft** [comment]
I am also aware of the problem and will provide a fix in the next days (the ForEach object idea was in fact my idea). The csv-writer problem is quite simple to solve (I guess), however I am still not happy about the way how to use custom datawriters. I will make a suggestion to tackle both problems.

**Comment by philippkraft** [comment]
A quick workaround might be in _algorithm.py _algorithm.__init__

Move `self.initialize_database()` behind `self.repeat.start()`. We have currently problems with our HPC cluster, @mop-mop , can you test this?

**Comment by thouska** [comment]
ok, I think this issue is solved.
