### ISSUE TITLE
Stop and restart optimisation

### ISSUE THREAD

**Issue by lu-kas** [thouska/spotpy#36]
Hi,

is it possible to restart / continue an optimisation?

I would like to be able to realise the following scenario:
1. Start optimisation
2. Stop optimisation
3. Write breakpoint data, i.e. all data needed for restart
4. Stop the whole process
5. Restart my applicaiton
6. Read breakpoint data
7. Continue optimisation, i.e. continue at step 2.

Best,
Lukas

**Comment by thouska** [comment]
Hi Lukas,
This is an interesting idea. So far, this continue setting is not possible yet. I will keep that in mind for further development. So far it is only possible to have a look at the .csv file during the optimization (I recommend to do a copy first, while the sampling is running).
Kind regards,
Tobias

**Comment by p-lauer** [comment]
Hi!

For algorithms like MC or FAST, where the samples are generated independetly, it seems easy to implement a restart function as you can stop them at any given time and restart. For evolutionary algorithms like SCE-UA it might be a bit harder, because you can't stop them at any given time without loosing/wasting data. It might be useful to be able to break after every generation.

If we come to an agreement on how we implement it, I could implement it for FSCABC and ABC, as there is already an array that holds the necessary data for a restart and just has to be dumped in a file.

I guess Lukas application is using the framework on a HPC-Cluster with a limited runtime per job. As you not necessarily can predict the runtime of a loop a priori, and the runtime of one loop can be several hours, we could include some automated writing of a restart file depending on current/remaining runtime.

Best regards

Patrick

**Comment by thouska** [comment]
Hi,

@p-lauer you are right, an implementation for MC, LHS and FAST should be no problem. It would be a nice feature. I am open for suggestions for an agreement that is useable by every algorithm, so that we can place the generation and restart possibilities into the base class of _algorithm.py. Ideas that I had so far would require many new dependencies for the existing algorithms, which would make the implementation of new algorithms harder. 
What do you think of starting step by step, i.e. implementing it for some algorithms to see how it goes? We could generate a backup/breakpoint file automatically every time after a user defined number of iteration, e.g. like: 

```sampler.sample(repetitions = 100000, backup_every_rep = 100)```

If the sampling stops before finishing because of whatever reason this file could be used to restart the sampling. I was thinking about a simple .txt file containing lines for i.a.:
Sampler name, user defined sampler keywords (repetitions, eb, a, etc.), current iteration, parameter array, objective function array, …
ABC and FSCABC are already very complex. I guess if an implementation works for them, a will also work for SCE-UA and others. @p-lauer it would be great if you want to start the implementation for the abc algorithms. I guess it should be possible to fit code than to the other algorithms.

Cheers,
Tobias

**Comment by p-lauer** [comment]
Sounds good. I'll try to find some time in the next two weeks to look into this and suggest an implementation.

**Comment by thouska** [comment]
Great, looks good. I run a first test with #40, which worked so far. 
As @p-lauer mentioned, there are some remaining issues. We will need a transfer of the backup reading and writing into ._algorithm as well as an adaption of the database calling. I'll try to do that in the upcoming days.

**Comment by thouska** [comment]
Ok, I moved the breakpoint reading/writing to .algorithm.py, so that it could be used by any of the algorithms. If breakpoint is set to 'read' or 'readandwrite', the csv file gets automatically appended.
The code should work now for fscabc.py.
@p-lauer: Could you run a test, if the code behaves like it should?

**Comment by p-lauer** [comment]
Hey Tobias,

looks good, thank you. Seems to work for me, though new data is not appended to the database, but the whole csv file is newly written.

**Comment by TristanHehnen** [comment]
Hello everybody!

Sorry for reviving this issue. 
I'm having some difficulties using the restart functionality with the SCE-UA. On the computing cluster I've access to are some time constrains in place, which kill every job after 24h. With my simulation setup the algorithm is not able to finish one generation before this time limit. 
In the way the resart functionality is implemented as of now it also seems that generation 0 (burn-in) is not able to write a breakpoint, thus the first one will in fact be written after the first two generations have passed, which for my case is way too long. 

Do you see a possibility to split the chunks, of when to write the breakpoints, into into smaller pieces, maybe even single repetitions? 


Small follow-up question: If I understood correctly, then the breakpoints are only written after a generation has finished and the parameter ´backup_every_rep = 100´ as a default means that 100 repetitions need to be performed for a breakpoint to be written. So, large jobs with more then 100 repetitions per generation dump after every generation that is processed, however smaller jobs with, say, 25 repetitions dump after 4 generations. 
Why not have the value default ´1´ so that the break points are written every generation, regardless?

Cheers,
Tristan

**Comment by TristanHehnen** [comment]
Hi Tobias,
we've checked my scripts again and it turned out that I've made an error somewhere else. This lead to a much longer execution than necessary, thus not a single generation could be finished. Now it is able to finish about five generations, which is sufficient (at least for now).

On the default value: Maybe it is better to leave it at 100 then. I'm slightly biased since the fastest simulations I could conduct takes about one minute.

**Comment by TristanHehnen** [comment]
Well, I guess this can be closed now,
Thanks!

**Comment by enervifa** [comment]
Hello, I have been using SPOTPY to run the DREAM algorithm and had a quick question. Is it currently possible to resume a DREAM run after it has finished or the session has ended? I could not find any option to save or reload the internal hyperparameter/state information, but I wanted to double-check in case I missed something.

I am coupling DREAM with an external model that takes a long time to run, so the ability to resume sampling (or any recommended workaround) would be extremely helpful. Alternatively, I might explore running shorter chunks or using the parallel option.

Thanks a lot for your work on SPOTPY and for any guidance you can provide!
Eliana
