### ISSUE TITLE
Tell the datawriter to only save certain runs

### ISSUE THREAD

**Issue by zutn** [thouska/spotpy#57]
Spotpy produces quite large output files when the model is run often or for a long calculated period. To avoid this it would be quite useful if one could tell spotpy to only save certain runs. This could be implemented by saving only those runs where "objectivefunction" returns not None.

**Comment by bees4ever** [comment]
Hi, I was trying to get such a idea to work, but I see that if `objectivefunction` is returning a different value as it usually does, say `None` or some `Enum` or `String`, it will change the logic in the used algorithms. Because they need the `objectivefunction` value for their logic and then they will appear differently. I looked up, how and if another idea can work. I propose it here and then if it is ok, I will commit it:

1. I add a new parameter to `_algorithm.py` which is called: `save_def`. This parameter can be `None` or a function. This is watching for conditions and then saving this line or not:

Example:

```python

def myCond(l):
    if l < 170:
        print("MyCond sent a False")
        return False
    else:
        return True

sampler=spotpy.algorithms.dream(spot_setup, ... ,save_def=myCond)
```


Now in `algorithm.py` it simply does:

```python
elif self.save_def(like):
   self.datawriter.save(like, randompar, simulations, chains=chains)
```


What do you think? Or is it not a problem with this *None* values in the algorithms logic?

**Comment by thouska** [comment]
thanks for your ideas. The way @bees4ever proposed is certainly a good way to go. I uploaded now a version, which might be a little bit easier to use than a `def mycond` function:

It is now possible to define a `save_threshold` value as keyword in the algorithm, e.g. like this:
```
from spotpy.examples.spot_setup_rosenbrock import spot_setup
sampler=spotpy.algorithms.mc(spot_setup(), 
dbname='RosenMC', dbformat='csv', save_threshold=-1000)
sampler.sample(5000)
results = sampler.getdata()
```

It is also possible to compare a list of objectivefunctions with a list of save_threshold values:
```
def objecttivefuntion(self,simulation,evaluation,params=None):
        objf1 = spotpy.objectivefunctions.r_squared(evaluation = evaluation, simulation = simulation)  
        objf2 = spotpy.objectivefunctions.rmse(evaluation = evaluation, simulation = simulation)
        return [objf1,objf2] 
```

And for the thresholds:
```
sampler=spotpy.algorithms.mc(spot_setup(), 
dbname='RosenMC', dbformat='csv', save_threshold=[0.7,200)
```

**Comment by zutn** [comment]
Thank you for the implementation. I might have found a bug. The way it is implemented not throws an error if more than one objective function is saved, but no threshold is defined, as in this case Spotpy tries to compare a float value with a list.

**Comment by zutn** [comment]
Proposed fix in new pull request.

**Comment by thouska** [comment]
cool, thanks for this fix. Seems to be a Python2/Python3 thing...
If you find any other bugs at this point, I am happy to hear about that, This is part is in testing phase.

**Comment by zutn** [comment]
Works like charm
